version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=clean_architecture
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      # - db:/var/lib/postgresql/data

# volumes:
  # db:
    # driver: local

# docker compose up -d
